### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by cafersamet** [oniongarlic/qt5-barcodevideofilter#1]
Hey, 
I tried to run this project in QT 5.8 with some additional configurations for Android platform but i got [install_target] Error. Do you have an idea about that issue?

**Comment by oniongarlic** [comment]
What is the exact error ? Note that you can't run this directly, it is a library.

**Comment by cafersamet** [comment]
I solved the problem. Project path is  "c++/../.." and these pluses make problem, I removed "++". Thanks bro..
